providers = ["node"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[phases.setup]
cmds = ["npx prisma migrate deploy"]

[start]
cmd = "npm start"
