providers = ["nodejs"]

[providers.nodejs]
version = "18"

[phases.setup]
nixPkgs = ["postgresql"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "npm start"

[env]
NODE_ENV = "production"
